#!/usr/bin/env bash
# Write a workspace landing page into a rustdoc output directory.
#
# rustdoc on the pinned stable toolchain does not emit target/doc/index.html
# for a workspace. GitHub/GitLab Pages and a downloaded artifact would 404
# at the site root without this. The page reuses rustdoc's hashed CSS/JS
# from static.files/ so the root matches the crate docs.
set -euo pipefail

DEST="${1:-target/doc}"
STATIC="$DEST/static.files"
if [ ! -d "$DEST" ]; then
  echo "rustdoc output not found at $DEST" >&2
  exit 1
fi
if [ ! -d "$STATIC" ]; then
  echo "rustdoc static.files not found at $STATIC" >&2
  exit 1
fi

pick() {
  local glob="$1"
  local -a matches
  shopt -s nullglob
  matches=("$STATIC"/$glob)
  shopt -u nullglob
  if [ "${#matches[@]}" -ne 1 ]; then
    echo "expected one $STATIC/$glob, found ${#matches[@]}" >&2
    exit 1
  fi
  basename "${matches[0]}"
}

NORMALIZE="$(pick 'normalize-*.css')"
RUSTDOC_CSS="$(pick 'rustdoc-*.css')"
NOSCRIPT="$(pick 'noscript-*.css')"
STORAGE_JS="$(pick 'storage-*.js')"
MAIN_JS="$(pick 'main-*.js')"
SEARCH_JS="$(pick 'search-*.js')"
SETTINGS_JS="$(pick 'settings-*.js')"
FAVICON_PNG="$(pick 'favicon-32x32-*.png')"
FAVICON_SVG="$(pick 'favicon-*.svg')"
RUST_LOGO="$(pick 'rust-logo-*.svg')"

font_csv=""
shopt -s nullglob
for f in "$STATIC"/*.woff2; do
  [ -z "$font_csv" ] || font_csv+=","
  font_csv+="$(basename "$f")"
done
shopt -u nullglob

crate_names=()
crate_hrefs=()
for index in "$DEST"/*/index.html; do
  [ -f "$index" ] || continue
  name="$(basename "$(dirname "$index")")"
  case "$name" in
    src|static.files|trait.impl|implementors|search.index) continue ;;
  esac
  crate_names+=("${name//_/-}")
  crate_hrefs+=("${name}/index.html")
done

{
  cat <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="rustdoc">
<meta name="description" content="OA-Gateway workspace rustdoc">
<title>OA-Gateway rustdoc</title>
EOF
  if [ -n "$font_csv" ]; then
    cat <<EOF
<script>if(window.location.protocol!=="file:")document.head.insertAdjacentHTML("beforeend","${font_csv}".split(",").map(f=>\`<link rel="preload" as="font" type="font/woff2" crossorigin href="./static.files/\${f}">\`).join(""))</script>
EOF
  fi
  cat <<EOF
<link rel="stylesheet" href="./static.files/${NORMALIZE}">
<link rel="stylesheet" href="./static.files/${RUSTDOC_CSS}">
<meta name="rustdoc-vars" data-root-path="./" data-static-root-path="./static.files/" data-current-crate="oa_gateway" data-themes="" data-resource-suffix="" data-search-js="${SEARCH_JS}" data-settings-js="${SETTINGS_JS}">
<script src="./static.files/${STORAGE_JS}"></script>
<script defer src="./static.files/${MAIN_JS}"></script>
<noscript><link rel="stylesheet" href="./static.files/${NOSCRIPT}"></noscript>
<link rel="alternate icon" type="image/png" href="./static.files/${FAVICON_PNG}">
<link rel="icon" type="image/svg+xml" href="./static.files/${FAVICON_SVG}">
</head>
<body class="rustdoc mod crate">
<nav class="mobile-topbar"><button class="sidebar-menu-toggle" title="show sidebar"></button><a class="logo-container" href="./index.html"><img class="rust-logo" src="./static.files/${RUST_LOGO}" alt=""></a></nav>
<nav class="sidebar">
<div class="sidebar-crate"><a class="logo-container" href="./index.html"><img class="rust-logo" src="./static.files/${RUST_LOGO}" alt="logo"></a><h2><a href="./index.html">OA-Gateway</a><span class="version">0.1.0</span></h2></div>
<div class="sidebar-elems">
<h2 class="location">Crates</h2>
<ul class="block">
EOF
  for i in "${!crate_names[@]}"; do
    printf '  <li><a href="%s">%s</a></li>\n' "${crate_hrefs[$i]}" "${crate_names[$i]}"
  done
  cat <<EOF
</ul>
</div>
</nav>
<div class="sidebar-resizer"></div>
<main>
<div class="width-limiter">
<rustdoc-search></rustdoc-search>
<section id="main-content" class="content">
<div class="main-heading"><h1>OA-Gateway</h1></div>
<div class="docblock">
<p>API docs generated by rustdoc. Private items are included so the host
binary's modules show up; library crates still lead with their public API.</p>
</div>
<h2 id="crates" class="section-header">Crates<a href="#crates" class="anchor">§</a></h2>
<ul class="item-table">
EOF
  for i in "${!crate_names[@]}"; do
    printf '  <li><div class="item-name"><a class="mod" href="%s">%s</a></div></li>\n' \
      "${crate_hrefs[$i]}" "${crate_names[$i]}"
  done
  cat <<'EOF'
</ul>
</section>
</div>
</main>
</body>
</html>
EOF
} >"$DEST/index.html"
