#!/usr/bin/env bash
# Write a workspace landing page into a rustdoc output directory.
#
# rustdoc on the pinned stable toolchain does not emit target/doc/index.html
# for a workspace. GitHub/GitLab Pages and a downloaded artifact would 404
# at the site root without this.
set -euo pipefail

DEST="${1:-target/doc}"
if [ ! -d "$DEST" ]; then
  echo "rustdoc output not found at $DEST" >&2
  exit 1
fi

{
  cat <<'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>OA-Gateway rustdoc</title>
</head>
<body>
<h1>OA-Gateway</h1>
<p>API docs generated by rustdoc. Private items are included so the host
binary's modules show up; library crates still lead with their public API.</p>
<ul>
EOF
  # Crate pages live in underscore-named directories. Skip rustdoc’s own
  # support trees so the list is only workspace members.
  for index in "$DEST"/*/index.html; do
    [ -f "$index" ] || continue
    name="$(basename "$(dirname "$index")")"
    case "$name" in
      src|static.files|trait.impl|implementors|search.index) continue ;;
    esac
    display="${name//_/-}"
    printf '  <li><a href="%s/index.html">%s</a></li>\n' "$name" "$display"
  done
  cat <<'EOF'
</ul>
</body>
</html>
EOF
} >"$DEST/index.html"
